### PR TITLE
FIX - Fixed some weird stuff, that is being marked by the IDE.

### PR DESCRIPTION
**Pull request by luko0610**
Fixed some things that is not accepted by my IDE.

### CODE REVIEW

**Comment by StrangeWill** [comment]
What is with removing all the switch expressions?

**Review by StrangeWill — CHANGES_REQUESTED** [review]
Don't remove newer C# features, specifically switch expressions.

**Comment by luko0610** [comment]
I reverted that. The problem isn't my IDE not supporting C# 8.0. I just wanted to get rid of that error below.

image
image

The rest should be okay.

**Review by ctyar — CHANGES_REQUESTED** [review]
Can you please squash and rebase your changes

**Comment by luko0610** [comment]
done

**Comment by ctyar** [comment]
Thank you @luko0610

**Comment by StrangeWill** [comment]
Are you using Resharper?

https://youtrack.jetbrains.com/issue/RSRP-476535

**Pull request merged**
