### PR TITLE
Move reservation total amount from clientside to API

### PR DESCRIPTION
**Pull request by ctyar**
Setting the amount for reservation in client-side is abusable, just moved the logic to back-end

### CODE REVIEW

**Comment by StrangeWill** [comment]
Yeah this was originally to allow for things like partial payments, deposits, etc. more like more traditional hotel setups.

**Comment by ctyar** [comment]
Oh, I didn't know that
@paulchrisluke If we are going to keep the partial payments this would be irrelevant

**Comment by paulchrisluke** [comment]
Only think I can think of is deposits. For browtricks, auto charging the card a deposit if the client no-shows is a nessessary feature.

**Comment by ctyar** [comment]
@paulchrisluke This doesn't cover that
This only lets the user pay a part of the full payment in the reservation process instead of the whole thing

**Pull request merged**
