### PR TITLE
Finishing up payment process

### PR DESCRIPTION
**Pull request by ctyar**
Deploy steps:

1. In Stripe dashboard go to [webhook settings](https://dashboard.stripe.com/webhooks)
2. Click “Add endpoint” and enter `/api/v0/reservations/paymentintent/confirm`, the Stripe API version, and select `PaymentIntentSucceeded` event.

2. Find the endpoint's secret in Stripe webhook settings in the Developer Dashboard and set the value in `appsettings.json`

We also need some minor changes in clients:
https://jsfiddle.net/ctyar/yg0c8nq5/

### CODE REVIEW

**Comment by paulchrisluke** [comment]
I've generated the secret and have it, but don't know how we are handling secrets... @StrangeWill ?

**Comment by StrangeWill** [comment]
They're put in Octopus Deploy, get it to me and I'll load it up (or I can probably pull it from Stripe).

**Comment by paulchrisluke** [comment]
@ctyar the secrets have been added, do you need a review from @StrangeWill to merge?

**Comment by ctyar** [comment]
@paulchrisluke It's always nice to have another set of eyes on the code but if we are short on time we can just merge

**Comment by StrangeWill** [comment]
One moment I'll take a look at this...

**Comment by StrangeWill** [comment]
Oh and minor comment: if we merge as-is, file an issue and refer to the changes above.

**Comment by paulchrisluke** [comment]
@ctyar how do you think it's take to do this refactor ? I'd rather do it now than later. Vkirirom is happy with the launch and we can buy some time to do this and tests

**Comment by paulchrisluke** [comment]
Note. I'll probably want to integrate with some sort of e-commerce tracking like 

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

Which may be worth considering at this stage. (Naming our database fields with matching stuff may make sense )

**Comment by ctyar** [comment]
@StrangeWill I fixed the coupling between reservations and payment.
Could you please clarify the second point. What do you mean by other modules and further processing?

**Pull request merged**
